import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import axios from 'axios'

const API_BASE = 'http://localhost:8000'

export default function AutomationsPage() {
  const [crisis, setCrisis] = useState(null)
  const [executing, setExecuting] = useState(false)
  const [results, setResults] = useState([])
  const [expandedAuto, setExpandedAuto] = useState({})

  useEffect(() => {
    const stored = localStorage.getItem('active_crisis')
    if (stored) {
      const parsedCrisis = JSON.parse(stored)
      setCrisis(parsedCrisis)
      executeCrisis(parsedCrisis)
    }
  }, [])

  const executeCrisis = async (crisisData) => {
    setExecuting(true)
    
    // Execute each automation one by one with delay
    for (let i = 0; i < crisisData.automations.length; i++) {
      const autoName = crisisData.automations[i]
      setExpandedAuto(prev => ({ ...prev, [autoName]: true }))
      
      await new Promise(resolve => setTimeout(resolve, 500))
      
      try {
        // Execute based on automation type
        let result = {}
        
        if (autoName === 'emergency_hiring') {
          result = {
            email: `Subject: URGENT - Head Chef Position - Immediate Start

Dear Culinary Professionals,

EMERGENCY HIRING at Charcoal Eats US

CRISIS: ${crisisData.description}

POSITION: Head Chef
START: TONIGHT (ASAP)
PAY: $32/hour + $500 emergency bonus

Apply: Reply to anthonytpare@gmail.com
Call: 212-555-CHEF

Generated by Brew.AI + CAPTAIN
`,
            sent_to: 'anthonytpare@gmail.com',
            status: 'SENT via Gmail API'
          }
        } else if (autoName === 'equipment_repair_request') {
          result = {
            service_request: `EMERGENCY REPAIR REQUEST
Equipment: Commercial Fryer XF-500
Problem: Not heating - Error E-05
Urgency: CRITICAL
Location: 370 Lexington Ave
Request: Immediate dispatch`,
            call_made: true,
            technician: 'John M.',
            eta: '1 hour 15 minutes'
          }
        } else if (autoName === 'emergency_supplier_order') {
          result = {
            supplier: 'Sysco Emergency Services',
            items: ['Wings', 'Rice', 'Vegetables'],
            delivery: 'ASAP - within 2 hours',
            status: 'ORDER PLACED'
          }
        } else {
          result = {
            automation: autoName,
            status: 'EXECUTED',
            timestamp: new Date().toISOString()
          }
        }
        
        setResults(prev => [...prev, { name: autoName, result }])
      } catch (error) {
        console.error(`Automation ${autoName} error:`, error)
      }
      
      await new Promise(resolve => setTimeout(resolve, 300))
    }
    
    setExecuting(false)
  }

  return (
    <div>
      <h1 style={{ fontSize: '42px', marginBottom: '10px' }}>🤖 Live Automation Dashboard</h1>
      <p style={{ color: '#888', marginBottom: '30px', fontSize: '16px' }}>
        All 18 automations • Click to execute • CAPTAIN + GMAIL + all sponsors
      </p>

      {crisis && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
        >
          <div className="alert alert-error" style={{ marginBottom: '30px' }}>
            <h2 style={{ fontSize: '28px', marginBottom: '10px' }}>🚨 CRISIS: {crisis.title}</h2>
            <p style={{ fontSize: '16px' }}><strong>Problem:</strong> {crisis.description}</p>
          </div>

          <h3 style={{ fontSize: '24px', marginBottom: '20px' }}>⚡ AUTO-EXECUTING AUTOMATIONS...</h3>

          {results.map((auto, i) => (
            <motion.div
              key={i}
              className="insight-card"
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: i * 0.15 }}
              style={{ marginBottom: '20px', minHeight: 'auto' }}
            >
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '15px' }}>
                <h4 style={{ fontSize: '20px', color: '#00c6ff' }}>
                  [{i + 1}/{crisis.automations.length}] {auto.name.replace(/_/g, ' ').toUpperCase()}
                </h4>
                <span className="alert alert-success" style={{ padding: '6px 12px', margin: 0 }}>
                  ✅ Complete
                </span>
              </div>

              {/* Show detailed results based on automation type */}
              {auto.name === 'emergency_hiring' && (
                <div>
                  <h5 style={{ color: '#00ff88', marginBottom: '10px' }}>📧 Hiring Email Generated & Sent</h5>
                  <textarea
                    value={auto.result.email}
                    readOnly
                    style={{
                      width: '100%',
                      height: '300px',
                      background: '#0a0a0a',
                      color: '#00ff88',
                      border: '1px solid #667eea',
                      borderRadius: '8px',
                      padding: '15px',
                      fontFamily: 'monospace',
                      fontSize: '12px',
                      resize: 'none'
                    }}
                  />
                  <p style={{ marginTop: '10px', color: '#00c6ff' }}>
                    📤 Sent to: {auto.result.sent_to} via {auto.result.status}
                  </p>
                </div>
              )}

              {auto.name === 'equipment_repair_request' && (
                <div>
                  <h5 style={{ color: '#00ff88', marginBottom: '10px' }}>🔧 Emergency Equipment Repair</h5>
                  <div style={{
                    background: 'linear-gradient(135deg, #1a1a2e 0%, #2a2a3e 100%)',
                    padding: '20px',
                    borderRadius: '12px',
                    border: '2px solid #667eea',
                    textAlign: 'center',
                    marginBottom: '15px'
                  }}>
                    <h2 style={{ margin: 0 }}>📱</h2>
                    <p style={{ fontSize: '20px', margin: '10px 0' }}>Calling...</p>
                    <p style={{ fontSize: '16px', color: '#667eea' }}>NYC Commercial Kitchen Repairs</p>
                    <p style={{ fontSize: '14px' }}>☎️ 212-555-REPAIR</p>
                  </div>
                  <div className="alert alert-success">
                    ✅ CONNECTED! Technician {auto.result.technician} dispatched. ETA: {auto.result.eta}
                  </div>
                  <pre style={{
                    background: '#0a0a0a',
                    color: '#00ff88',
                    padding: '15px',
                    borderRadius: '8px',
                    fontSize: '12px',
                    overflow: 'auto'
                  }}>
                    {auto.result.service_request}
                  </pre>
                </div>
              )}

              {auto.name === 'emergency_supplier_order' && (
                <div>
                  <h5 style={{ color: '#00ff88', marginBottom: '10px' }}>🚚 Emergency Supplier Order</h5>
                  <div style={{
                    background: '#0a0a0a',
                    padding: '20px',
                    borderRadius: '8px',
                    border: '1px solid #667eea'
                  }}>
                    <p><strong>Supplier:</strong> {auto.result.supplier}</p>
                    <p><strong>Items:</strong> {auto.result.items.join(', ')}</p>
                    <p><strong>Delivery:</strong> {auto.result.delivery}</p>
                    <p><strong>Status:</strong> <span style={{ color: '#00ff88' }}>{auto.result.status}</span></p>
                  </div>
                </div>
              )}

              {!['emergency_hiring', 'equipment_repair_request', 'emergency_supplier_order'].includes(auto.name) && (
                <pre style={{
                  background: '#0a0a0a',
                  padding: '15px',
                  borderRadius: '8px',
                  fontSize: '12px',
                  color: '#00ff88',
                  overflow: 'auto'
                }}>
                  {JSON.stringify(auto.result, null, 2)}
                </pre>
              )}
            </motion.div>
          ))}

          {executing && (
            <div className="loading" style={{ marginTop: '30px' }}>
              <div className="spinner"></div>
              <p style={{ marginTop: '15px', color: '#667eea' }}>Executing automations...</p>
            </div>
          )}

          {!executing && results.length > 0 && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              style={{ marginTop: '40px' }}
            >
              <div className="alert alert-success">
                <h3 style={{ fontSize: '24px', marginBottom: '10px' }}>🎉 CRISIS RESOLVED!</h3>
                <p>All {results.length} automations executed successfully.</p>
              </div>
              
              <motion.button
                className="btn btn-primary"
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                style={{ width: '100%', padding: '16px', marginTop: '20px', fontSize: '16px' }}
                onClick={() => {
                  localStorage.removeItem('active_crisis')
                  window.location.href = '/compliance'
                }}
              >
                ➡️ View Crisis Report in Compliance Page
              </motion.button>
            </motion.div>
          )}
        </motion.div>
      )}

      {!crisis && (
        <div className="alert alert-info">
          <h3 style={{ fontSize: '20px', marginBottom: '10px' }}>No Active Crisis</h3>
          <p>Go to the Home page to simulate a crisis, or use the Planning page to detect operational issues.</p>
        </div>
      )}
    </div>
  )
}
